<?php
echo "<div align=\"center\"><b>Алхимия</b> (33)</div>\r\n<br>\r\n\r\n<div align=\"justify\" class=small>\r\nПознания в алхимии необходимы для приготовления эликсиров. Вам понадобятся находиться в лаборатории и иметь в руках подходящие лечебные травы и свиток. Используйте функции лаборатории для создания интересующего Вас эликсира.\r\n</div><br>\r\n<div align=\"center\"><b>Таблица приготовления эликсиров</b></div>\r\n<table width=90% al";
echo "ign=center>\r\n<tr><td width=60><img src=maingame/pic/stuff/buttle/buttle3.gif width=60 height=60></td><td><b>Название:</b> Свиток здоровья<br><b>Материал: </b> 2 Шерпень<br><b>Необходимый:</b> 1 урок</td></tr>\r\n<tr><td width=60><img src=maingame/pic/stuff/buttle/buttle1.gif width=60 height=60></td><td><b>Название:</b> Свиток энергии<br><b>Материал: </b> 1 Шерпень, 1 Очиток<br><b>Необходимый:</b> 5 уроков</td></tr>\r\n<tr><td width=";
echo "60><img src=maingame/pic/stuff/buttle/buttle9.gif width=60 height=60></td><td><b>Название:</b> Свиток заживления<br><b>Материал: </b> 2 Очиток<br><b>Необходимый:</b> 10 уроков</td></tr>\r\n<tr><td width=60><img src=maingame/pic/stuff/buttle/buttle5.gif width=60 height=60></td><td><b>Название:</b> Свиток смелости<br><b>Материал: </b>  2 Очиток, 1 Женьшень<br><b>Необходимый:</b> 16 уроков</td></tr>\r\n<tr><td width=60><img src=mainga";
echo "me/pic/stuff/buttle/buttle7.gif width=60 height=60></td><td><b>Название:</b> Свиток ясного ума<br><b>Материал: </b> 2 Женьшень, 1 Очиток<br><b>Необходимый:</b> 18 уроков</td></tr>\r\n<tr><td width=60><img src=maingame/pic/stuff/buttle/buttle10.gif width=60 height=60></td><td><b>Название:</b> Свиток движения<br><b>Материал: </b>  2 Женьшень, 1 Лапчатка<br><b>Необходимый:</b> 21 уроков</td></tr>\r\n<tr><td width=60><img src=maingame";
echo "/pic/stuff/buttle/buttle6.gif width=60 height=60></td><td><b>Название:</b> Свиток ясного зрения<br><b>Материал: </b> 2 Лапчатка, 1 Иссоп<br><b>Необходимый:</b> 24 урока</td></tr>\r\n<tr><td width=60><img src=maingame/pic/stuff/buttle/buttle8.gif width=60 height=60></td><td><b>Название:</b> Свиток скорости<br><b>Материал: </b> 2 Иссоп, 1 Лапчатка<br><b>Необходимый навык:</b> 28 уроков</td></tr>\r\n<tr><td width=60><img src=maingame";
echo "/pic/stuff/buttle/buttle2.gif width=60 height=60></td><td><b>Название:</b> Свиток выносливости<br><b>Материал: </b> 1 Вахта, 3 Иссоп<br><b>Необходимый навык:</b> 32 урока</td></tr>\r\n<tr><td width=60><img src=maingame/pic/stuff/buttle/buttle4.gif  width=60 height=60></td><td><b>Название:</b> Свиток восстановления<br><b>Материал: </b> 1 Иссоп, 3 Вахта<br><b>Необходимый навык:</b> 33 урока</td></tr>\r\n\r\n</table>\r\n<br>\r\n<div align=";
echo "\"center\"><b>Изготовление эликсиров</b></div><br>\r\n\r\n<div align=\"justify\" class=small>\r\nПрочитайте содержимое свитка, нажав на него в инвентаре, после чего найдите подходящую комнату с функцией лаборатории.<br><br>\r\n<div align=center><img src=help/elik.gif border=1></div><br>\r\nЗаполните появившуюся форму в соответствии со свитком и нажмите на кнопку <b>'Изготовить'</b>.<br>\r\n<br>\r\nПри неудачной попытке отнимется ";
echo "только по 1 единицы каждого ресурса.\r\n</div><br>\r\n<br>\r\n<br>\r\n<b><div align=\"center\"><a href=index.php?load=";
print "{$load}";
echo "&show=";
print $show;
echo ">Назад</div></b><br>\r\n";
?>
