<?php

echo "<div align=\"center\"><b>Изготовление доспехов</b> (50)</div>\r\n<br>\r\n\r\n<div align=\"justify\" class=small>\r\nПознания в этом умении дают вашему персонажу возможность ковать защитные предметы любой сложности. Вам понадобятся находиться в кузнице и иметь в руках подходящие слитки металлов, молот и свиток желаемого предмета. Используйте функции кузницы для создания интересующего Вас предмета. Чем выше Ваше знан";
echo "ие в этом умении, чем больше шанс изготовить предмет с повышенными характеристиками.\r\n</div><br>\r\n<div align=\"center\"><b>Таблица изготовления доспехов</b></div>\r\n<table width=90% align=center>\r\n\r\n<tr><td width=70 align=center><img src=maingame/pic/stuff/helmet/helmet5.gif></td><td><b>Название:</b> Открытый шлем<br><b>Материал: </b>4 Железо<br><b>Необходимый навык:</b> 1 урок</td></tr>\r\n<tr><td width=70 align=center><img s";
echo "rc=maingame/pic/stuff/shield/shield1.gif></td><td><b>Название:</b> Круглый щит<br><b>Материал: </b> 3 Железа<br><b>Необходимый навык:</b> 2 урока</td></tr>\r\n<tr><td width=70 align=center><img src=maingame/pic/stuff/glove/glove5.gif></td><td><b>Название:</b> Перчатки рыцаря<br><b>Материал: </b> 2 Бронзы, 2 Железа<br><b>Необходимый навык:</b> 3 урока</td></tr>\r\n<tr><td width=70 align=center><img src=maingame/pic/stuff/armor/armo";
echo "r5.gif></td><td><b>Название:</b> Лёгкая кольчуга<br><b>Материал: </b> 4 Бронзы<br><b>Необходимый навык:</b> 8 уроков</td></tr>\r\n<tr><td width=70 align=center><img src=maingame/pic/stuff/helmet/helmet.gif></td><td><b>Название:</b> Шлем `Утка`<br><b>Материал: </b>4 Железо, 4 Серебра<br><b>Необходимый навык:</b> 12 уроков</td></tr>\r\n<tr><td width=70 align=center><img src=maingame/pic/stuff/armor/armor4.gif></td><td><b>Название:</b> Л";
echo "ёгкие доспехи<br><b>Материал: </b> 5 Железа<br><b>Необходимый навык:</b> 15 уроков</td></tr>\r\n<tr><td width=70 align=center><img src=maingame/pic/stuff/glove/glove2.gif></td><td><b>Название:</b> Золотые перчатки<br><b>Материал: </b> 2 Серебра, 5 Золота<br><b>Необходимый навык:</b> 19 уроков</td></tr>\r\n<tr><td width=70 align=center><img src=maingame/pic/stuff/armor/armor7.gif></td><td><b>Название:</b> Кольчуга<br><b>Материал: </b>";
echo " 5 Железа, 5 Серебро<br><b>Необходимый навык:</b> 22 урока</td></tr>\r\n<tr><td width=70 align=center><img src=maingame/pic/stuff/shield/shield4.gif></td><td><b>Название:</b> Угловатый щит<br><b>Материал: </b> 10 Роза<br><b>Необходимый навык:</b> 25 урока</td></tr>\r\n<tr><td width=70 align=center><img src=maingame/pic/stuff/helmet/helmet4.gif></td><td><b>Название:</b> Закрытый шлем<br><b>Материал: </b> 10 Ветрий<br><b>Необходимый н";
echo "авык:</b> 28 уроков</td></tr>\r\n<tr><td width=70 align=center><img src=maingame/pic/stuff/armor/armor9.gif></td><td><b>Название:</b> Доспехи тамплиеров<br><b>Материал: </b> 10 Крентаврий<br><b>Необходимый навык:</b> 33 урока</td></tr>\r\n<tr><td width=70 align=center><img src=maingame/pic/stuff/shield/shield7.gif></td><td><b>Название:</b> Гиперион<br><b>Материал: </b> 2 Серебра, 10 Ветрий<br><b>Необходимый навык:</b> 38 уроков</td>";
echo "</tr>\r\n<tr><td width=70 align=center><img src=maingame/pic/stuff/glove/glove4.gif></td><td><b>Название:</b> Латные перчатки<br><b>Материал: </b> 2 Ветрий, 10 Крентаврий<br><b>Необходимый навык:</b> 43 урока</td></tr>\r\n<tr><td width=70 align=center><img src=maingame/pic/stuff/helmet/helmet7.gif></td><td><b>Название:</b> Шлем меченосца<br><b>Материал: </b> 10 Ветрий, 10 Крентаврий<br><b>Необходимый навык:</b> 46 уроков</td></tr>\r";
echo "\n<tr><td width=70 align=center><img src=maingame/pic/stuff/shield/shield9.gif></td><td><b>Название:</b> Щит победителя<br><b>Материал: </b> 10 Серебра, 10 Крентаврий<br><b>Необходимый навык:</b> 49 уроков</td></tr>\r\n<tr><td width=70 align=center><img src=maingame/pic/stuff/armor/armor11.gif></td><td><b>Название:</b> Доспехи призрака<br><b>Материал: </b> 8 Ветрий, 10 Крентаврий<br><b>Необходимый навык:</b> 50 уроков</td></tr>\r\n";
echo "\r\n</table>\r\n<br>\r\n<table width=90% align=center>\r\n<tr><td width=70><img src=maingame/pic/stuff/hammer/hammer9.gif></td><td><b>Инструмент для ковки:</b> Молот кузнеца<br></td></tr>\r\n\r\n</table>\r\n\r\n\r\n<br>\r\n<div align=\"center\"><b>Изготовление доспехов</b></div><br>\r\n\r\n<div align=\"justify\" class=small>\r\nПрочитайте содержимое свитка, нажав на него в инвентаре, после чего найдите подходящую комнату с функцией кузницы.<br><br>\r";
echo "\n<div align=center><img src=help/black.gif border=1></div><br>\r\nЗаполните появившуюся форму в соответствии со свитком и нажмите на кнопку <b>'Изготовить'</b>.<br><br>\r\nПри неудачной попытке отнимется только по 1 единицы каждого ресурса.\r\n\r\n</div><br>\r\n<br>\r\n<br>\r\n<b><div align=\"center\"><a href=index.php?load=";
print "{$load}";
echo "&show=";
print $show;
echo ">Назад</div></b><br>\r\n";
?>
