<?php

echo "<div align=\"center\"><b>Оружейное дело</b> (50)</div>\r\n<br>\r\n\r\n<div align=\"justify\" class=small>\r\nПознания в оружейном деле дают вашему персонажу возможность ковать оружие любой сложности. Вам понадобятся находиться в кузнице и иметь в руках подходящие слитки металлов, молот и свиток желаемого предмета. Используйте функции кузницы для создания интересующего Вас предмета. Чем выше Ваше знание в этом умени";
echo "и, чем больше шанс изготовить предмет с повышенными характеристиками.\r\n</div><br>\r\n<div align=\"center\"><b>Таблица изготовления оружия</b></div>\r\n<table width=90% align=center>\r\n<tr><td width=70><img src=maingame/pic/stuff/knife/knife3.gif></td><td><b>Название:</b> Нож<br><b>Материал: </b> 2 Бронзы<br><b>Необходимый навык:</b> 1 урок</td></tr>\r\n<tr><td width=70><img src=maingame/pic/stuff/sword/sword8.gif></td><td><b>Название";
echo ":</b> Межный меч<br><b>Материал: </b> 2 Бронзы, 1 Железа<br><b>Необходимый навык:</b> 2 урока</td></tr>\r\n<tr><td width=70><img src=maingame/pic/stuff/axe/axe1.gif></td><td><b>Название:</b> Топор<br><b>Материал: </b> 2 Железа<br><b>Необходимый навык:</b> 4 урока</td></tr>\r\n<tr><td width=70><img src=maingame/pic/stuff/hammer/hammer2.gif></td><td><b>Название:</b> Булава<br><b>Материал: </b> 1 Бронзы, 3 Железа<br><b>Необходимый навык:</b";
echo "> 4 урока</td></tr>\r\n<tr><td width=70><img src=maingame/pic/stuff/axe/axe3.gif></td><td><b>Название:</b> Секира<br><b>Материал: </b>  10 Железо<br><b>Необходимый навык:</b> 10 уроков</td></tr>\r\n<tr><td width=70><img src=maingame/pic/stuff/knife/knife2.gif></td><td><b>Название:</b> Золотой кортик<br><b>Материал: </b> 4 Золота <br><b>Необходимый навык:</b> 14 уроков</td></tr>\r\n<tr><td width=70><img src=maingame/pic/stuff/hammer/hamme";
echo "r4.gif></td><td><b>Название:</b> Трехглавая Булава<br><b>Материал: </b>  3 Железа, 5 Серебра<br><b>Необходимый навык:</b> 22 урока</td></tr>\r\n<tr><td width=70><img src=maingame/pic/stuff/sword/sword3.gif></td><td><b>Название:</b> Длинный меч<br><b>Материал: </b> 4 Железа, 4 Роза<br><b>Необходимый навык:</b> 28 уроков</td></tr>\r\n<tr><td width=70><img src=maingame/pic/stuff/knife/knife5.gif></td><td><b>Название:</b> Широкий нож<br><b>";
echo "Материал: </b> 4 Роза, 3 Серебро <br><b>Необходимый навык:</b> 32 урока</td></tr>\r\n<tr><td width=70><img src=maingame/pic/stuff/sword/sword5.gif></td><td><b>Название:</b> Гладиус<br><b>Материал: </b> 3 Роза, 5 Серебра <br><b>Необходимый навык:</b> 38 уроков</td></tr>\r\n<tr><td width=70><img src=maingame/pic/stuff/hammer/hammer6.gif></td><td><b>Название:</b> Молот Орка<br><b>Материал: </b>  3 Роза, 6 Ветрий<br><b>Необходимый навык:";
echo "</b> 43 урока</td></tr>\r\n<tr><td width=70><img src=maingame/pic/stuff/axe/axe6.gif></td><td><b>Название:</b> Позолоченный топор<br><b>Материал: </b>  15 Золота, 2 Ветрий<br><b>Необходимый навык:</b> 45 уроков</td></tr>\r\n<tr><td width=70><img src=maingame/pic/stuff/knife/knife6.gif></td><td><b>Название:</b> Кинжал убийцы<br><b>Материал: </b> 10 Крентаврий, 5 Золота<br><b>Необходимый навык:</b> 46 уроков</td></tr>\r\n<tr><td width=70><i";
echo "mg src=maingame/pic/stuff/sword/sword7.gif></td><td><b>Название:</b> Меч Света<br><b>Материал: </b> 10 Ветрий, 5 Крентаврий<br><b>Необходимый навык:</b> 48 уроков</td></tr>\r\n<tr><td width=70><img src=maingame/pic/stuff/sword/sword6.gif></td><td><b>Название:</b> Меч Тьмы<br><b>Материал: </b> 5 Ветрий, 10 Крентаврий<br><b>Необходимый навык:</b> 48 уроков</td></tr>\r\n<tr><td width=70><img src=maingame/pic/stuff/axe/axe7.gif></td><td";
echo "><b>Название:</b> Проклятая секира<br><b>Материал: </b>  16 Крентаврий<br><b>Необходимый навык:</b> 50 уроков</td></tr>\r\n<tr><td width=70><img src=maingame/pic/stuff/hammer/hammer8.gif></td><td><b>Название:</b> Магический молот<br><b>Материал: </b>  10 Ветрий, 10 Крентаврий<br><b>Необходимый навык:</b> 50 уроков</td></tr>\r\n\r\n</table>\r\n<br>\r\n<table width=90% align=center>\r\n<tr><td width=70><img src=maingame/pic/stuff/hammer/hamm";
echo "er9.gif></td><td><b>Инструмент для ковки:</b> Молот кузнеца<br></td></tr>\r\n\r\n</table>\r\n\r\n<br>\r\n<div align=\"center\"><b>Изготовление оружия</b></div><br>\r\n\r\n<div align=\"justify\" class=small>\r\nПрочитайте содержимое свитка, нажав на него в инвентаре, после чего найдите подходящую комнату с функцией кузницы.<br><br>\r\n<div align=center><img src=help/black.gif border=1></div><br>\r\nЗаполните появившуюся форму в соответствии с";
echo "о свитком и нажмите на кнопку <b>'Изготовить'</b>.<br><br>\r\nПри неудачной попытке отнимется только по 1 единицы каждого ресурса.\r\n\r\n</div><br>\r\n<br>\r\n<br>\r\n<b><div align=\"center\"><a href=index.php?load=";
print "{$load}";
echo "&show=";
print $show;
echo ">Назад</div></b><br>\r\n";
?>
