<?php

echo "<div align=\"center\"><b>Клан</b></div><br>\r\n\r\n<div align=\"justify\" class=small>\r\nПри желании группа людей может создать клан. <br><br>\r\n\r\nДля этого необходимо:<br>\r\n<table width=99% align=center>\r\n<tr><Td class=\"small\"><div align=\"justify\" class=small>А) Количество персонажей готовых вступить не меньше 4.</div></td></tr>\r\n<tr><Td class=\"small\"><div align=\"justify\" class=small>Б) Иметь название и символику (Лого), соо";
echo "тветствующую тематике игры.</div></td></tr>\r\n<tr><Td class=\"small\"><div align=\"justify\" class=small>В) Иметь устав, историю и цели, которые отличаются от других кланов в игре.</div></td></tr>\r\n<tr><Td class=\"small\"><div align=\"justify\" class=small>Г) Иметь полупрофессиональную / профессиональную страничку, где описана полная информация о клане.</div></td></tr>\r\n<tr><Td class=\"small\"><div align=\"justify\" class=small";
echo ">Д) Уровень всех членов клана должен быть выше 10.</div></td></tr>\r\n</table><br>\r\n\r\nСамое главное отличие клановой системы Шамаал Ворлд заключается в возможности <i>'роста'</i>. Введены три ранга кланов. При получении следующего ранга, у кланов будут появляться новые возможности, такие как заключение договоров, должностная и финансовая система.<br>\r\n<br>\r\n";
echo "</b></a>\r\n<br>\r\n<br>\r\n\r\n<br>\r\n\r\n<div align=\"center\"><b>Ранг первый - Сообщество.</b></div><br>\r\n\r\nСообщество является самой простой общественной единицей, а поэтому не имеет много функций.<br><br>\r\n\r\nНовые возможности:<br>\r\n<table width=99% align=center>\r\n<tr><Td class=\"small\"><div align=\"justify\" class=small>А) Лого и значок клана.</div></td></tr>";
echo "\r\n<tr><Td class=\"small\"><div align=\"justify\" class=small>Б) Управление жителями.</div></td></tr>\r\n<tr><Td class=\"small\"><div align=\"justify\" class=small>В) Система новости.</div></td></tr>\r\n</table><br>\r\n<div align=\"center\"><b>Ранг второй - Братство.</b></div><br>\r\n\r\nДля получения второго ранга сообществу необходимо показать свою надобность в игровом мире Шамаал Ворлд.<br>\r\n<br>\r\nНовые возможности:<br>\r\n<table width=99%";
echo " align=center>\r\n<tr><Td class=\"small\"><div align=\"justify\" class=small>А) Должности</div></td></tr>\r\n<tr><Td class=\"small\"><div align=\"justify\" class=small>Б) Финансы</div></td></tr>\r\n<tr><Td class=\"small\"><div align=\"justify\" class=small>В) Переговоры</div></td></tr>\r\n<tr><Td class=\"small\"><div align=\"justify\" class=small>Г) Договоры</div></td></tr>\r\n</table><br>\r\n<div align=\"center\"><b>Ранг третий - Орден.</b></div><br>\r\n\r\nДл";
echo "я получения третьего ранга Братству необходимо полностью отстоять и зарекомендовать себя как один из самых сильных и влиятельных кланов в игре. А также иметь высокопрофессиональный сайт с очень подробной информацией и новостями, как самого клана, так и игрового мира Старый Шамаал Ворлд. <br>\r\n<br>\r\nС получением третьего ранга каждый член клана сможет взять уникальное Кольцо Ордена, параметры которого сможе";
echo "т увеличивать глава клана за счёт казны. Конечные параметры кольца не превышают обычные параметры игрового кольца, но само ювелирное изделие даёт уникальный отличительный знак и надпись(гравировка).\r\n<br>\r\n<br>\r\n\r\n</div>\r\n<b><div align=\"center\"><a href=index.php?load=";
print "{$load}";
echo ">Назад</div></b><br>\r\n";
?>
