<?php

echo "<b><div align=\"center\">Эликсиры</div></b><br>\r\n\r\n<b>Эликсиры</b> - небольшие бутылочки с жидкостями используемые в повседневной жизни.<br><br>\r\n<i>* Эликсиры может изготовить алхимик из свитка и нужных реагентов.</i><br><br>\r\n\r\n<b><div align=\"center\">Эликсиры и их эффекты</div></b><br>\r\n\r\n<table>\r\n<tr>\r\n\t<td><img src=maingame/pic/stuff/buttle/buttle3.gif></td>\r\n\t<td valign=top>Название: <b>Здоровье</b><br><br><i class=small>Д";
echo "анный эликсир увеличивает текущее здоровье персонажа на 1/10 от максимального количества жизней.</i></td>\r\n</tr>\r\n<tr>\r\n\t<td><img src=maingame/pic/stuff/buttle/buttle4.gif></td>\r\n\t<td valign=top>Название: <b>Восстановление</b><br><br><i class=small>Данный эликсир увеличивает текущее здоровье персонажа на 1/5 от максимального количества жизней.</i></td>\r\n</tr>\r\n<tr>\r\n\t<td><img src=maingame/pic/stuff/buttle/buttle1.gi";
echo "f></td>\r\n\t<td valign=top>Название: <b>Энергия</b><br><br><i class=small>Данный эликсир увеличивает силы персонажа на 1/10 от максимального количества энергии.</i></td>\r\n</tr>\r\n<tr>\r\n\t<td><img src=maingame/pic/stuff/buttle/buttle2.gif></td>\r\n\t<td valign=top>Название: <b>Выносливость</b><br><br><i class=small>Данный эликсир увеличивает силы персонажа на 1/5 от максимального количества энергии.</i></td>\r\n</tr>\r\n<tr>\r\n\t<td><im";
echo "g src=maingame/pic/stuff/buttle/buttle5.gif></td>\r\n\t<td valign=top>Название: <b>Смелость</b><br><br><i class=small>Данный эликсир снимает любой страх с вашего персонажа.</i></td>\r\n</tr>\r\n<tr>\r\n\t<td><img src=maingame/pic/stuff/buttle/buttle10.gif></td>\r\n\t<td valign=top>Название: <b>Движения</b><br><br><i class=small>Данный эликсир снимает парализацию с вашего персонажа.</i></td>\r\n</tr>\r\n\r\n<tr>\r\n\t<td><img src=maingame/pic/st";
echo "uff/buttle/buttle6.gif></td>\r\n\t<td valign=top>Название: <b>Ясное зрение</b><br><br><i class=small>Данный эликсир не только вылечивает от слепоты, но и увеличивает зоркость и бдительность вашего персонажа.</i></td>\r\n</tr>\r\n<tr>\r\n\t<td><img src=maingame/pic/stuff/buttle/buttle8.gif></td>\r\n\t<td valign=top>Название: <b>Скорость</b><br><br><i class=small>Данный эликсир увеличивает скорость восстановления баланса у вашего п";
echo "ерсонажа.</i></td>\r\n</tr>\r\n<tr>\r\n\t<td><img src=maingame/pic/stuff/buttle/buttle7.gif></td>\r\n\t<td valign=top>Название: <b>Ясность ума</b><br><br><i class=small>Данный эликсир выводит вашего персонажа из глубокого сна.</i></td>\r\n</tr>\r\n<tr>\r\n\t<td><img src=maingame/pic/stuff/buttle/buttle9.gif></td>\r\n\t<td valign=top>Название: <b>Заживление ран</b><br><br><i class=small>Данный эликсир снимает кровотечение с вашего персонажа.</i";
echo "></td>\r\n</tr>\r\n\r\n</table>\r\n<br>\r\n<br><b><div align=\"center\">Применение</div></b><br>\r\n&nbsp;&nbsp;&nbsp;&nbsp;При нажатии на эликсир в инвентаре или же в пункте меню `боевые действия` происходит автоматическое применение выбранного эликсира. Скорость восстановления баланса эликсиров зависит от расы вашего персонажа.\r\n<br><br>\r\n<div align=center>\r\n<img src=\"help/elix1.gif\" width=\"265\" height=\"233\" border=\"1\">\r\n<i";
echo "mg src=\"help/elix2.gif\" border=\"1\">\r\n</div>\r\n<br>\r\n<br>\r\n<b><div align=\"center\"><a href=index.php?load=";
print "{$load}";
echo ">Назад</div></b><br>";
?>
