<?php

echo "<div align=\"center\"><b>Магия огня</b> (50)</div>\r\n<br>\r\n\r\n<div align=\"justify\" class=small>\r\nЭто умение позволяет повысить урон и серьезность наносимых повреждений магией огня. Чем выше способности в этом умении, тем больше урон.  Для использования умения необходимо иметь в руках посох и соответствующий свиток в книге заклинаний, в противном случае способность не появятся в списке действий.\r\n</div><br>\r\n<d";
echo "iv align=\"center\"><b>Таблица Магии огня</b></div>\r\n<table width=95% align=center bgcolor=A5B2B5 cellspacing=1>\r\n<tr bgcolor=E7EBDE><td width=30 align=center  class=small><b>УР</b></td><td class=small><b>Название</b></td><td class=small><b>Описание</b></td><td width=60  align=center class=small><b>Энергия</b></td></tr>\r\n<tr bgcolor=F0F8F0><td width=30 align=center class=small>1</td><td class=small width=120>Огненная стрела</";
echo "td><td class=small>Наносит слабый урон противнику с 10%-ным шансом ожога(3).</td><td width=60  align=center class=small>10</td></tr>\r\n<tr bgcolor=F0F8F0><td width=30 align=center class=small>8</td><td class=small width=120>Проклятие</td><td class=small>Проклинает(8) противника.</td><td width=60  align=center class=small>20</td></tr>\r\n<tr bgcolor=F0F8F0><td width=30 align=center class=small>15</td><td class=small wid";
echo "th=120>Огненный шар</td><td class=small>Наносит средний урон с 10%-ным шансом ожога(5).</td><td width=60  align=center class=small>25</td></tr>\r\n<tr bgcolor=F0F8F0><td width=30 align=center class=small>25</td><td class=small width=120>Жажда крови</td><td class=small>Повышает жажду крови(5) у выбранной цели.</td><td width=60  align=center class=small>40</td></tr>\r\n<tr bgcolor=F0F8F0><td width=30 align=center class=s";
echo "mall>38</td><td class=small width=120>Слепота</td><td class=small>Ослепляет(3) противника с 50%-ным шансом.</td><td width=60  align=center class=small>60</td></tr>\r\n<tr bgcolor=F0F8F0><td width=30 align=center class=small>45</td><td class=small width=120>Огненное дыхание</td><td class=small>Наносит очень сильный урон с 35%-ным шансом ожога(6).</td><td width=60  align=center class=small>60</td></tr>\r\n</table>\r\n<br>\r\n<d";
echo "iv align=\"center\"><b>Действия</b></div>\r\n<table width=95% align=center cellspacing=1 cellpadding=3>\r\n<tr><td width=30><img src=maingame/pic/stuff/aff/11.gif width=25 height=25></td><td>Ожоги - Уменьшает защиту противника на 25%</td></tr>\r\n<tr><td width=30><img src=maingame/pic/stuff/aff/8.gif width=25 height=25></td><td>Проклятие - Уменьшает атаку противника на 25%</td></tr>\r\n<tr><td width=30><img src=maingame/pic/stu";
echo "ff/aff/9.gif width=25 height=25></td><td>Жажда крови - Увеличивает атаку на 40%</td></tr>\r\n<tr><td width=30><img src=maingame/pic/stuff/aff/10.gif width=25 height=25></td><td>Слепота - Полностью блокирует атаки персонажа</td></tr>\r\n</table>\r\n<br>\r\n<br>\r\n<b><div align=\"center\"><a href=index.php?load=";
print "{$load}";
echo "&show=";
print $show;
echo ">Назад</div></b><br>\r\n";
?>
