<?php

echo "<div align=\"center\"><b>Ювелирное дело</b> (33)</div>\r\n<br>\r\n\r\n<div align=\"justify\" class=small>\r\nПознания в этом умении дают вашему персонажу возможность изготавливать кольца и ожерелья из драгоценного металла. Вам понадобятся находиться в около Ювелирной мастерской и иметь в руках подходящие материалы и свиток желаемого предмета. Используйте функции ювелирной мастерской для создания интересующего Вас п";
echo "редмета. Чем выше Ваше знание в этом умении, чем больше шанс изготовить предмет с повышенными характеристиками.\r\n</div><br>\r\n<div align=\"center\"><b>Таблица изготовления драгоценных предметов</b></div>\r\n<table width=90% align=center>\r\n<tr><td width=70 align=center><img src=maingame/pic/stuff/amulet/amulet7.gif></td><td><b>Название:</b> Амулет<br><b>Материал: </b> 1 Бронза, 2 Топаз<br><b>Необходимый навык:</b> 1 урок</t";
echo "d></tr>\r\n<tr><td width=70 align=center><img src=maingame/pic/stuff/ring/ring5.gif></td><td><b>Название:</b> Кольцо любви<br><b>Материал: </b> 1 Золото, 1 Топаз, 2 Родолит<br><b>Необходимый навык:</b> 8 уроков</td></tr>\r\n<tr><td width=70 align=center><img src=maingame/pic/stuff/amulet/amulet1.gif></td><td><b>Название:</b> Ожерелье ветра<br><b>Материал: </b> 1 Железа, 4 Топаз, 4 Родолит<br><b>Необходимый навык:</b> 13 уроков</td";
echo "></tr>\r\n<tr><td width=70 align=center><img src=maingame/pic/stuff/ring/ring8.gif></td><td><b>Название:</b> Кольцо Сирены<br><b>Материал: </b> 1 Золото, 2 Родолит, 3 Розовый Сапфир<br><b>Необходимый навык:</b> 16 уроков</td></tr>\r\n<tr><td width=70 align=center><img src=maingame/pic/stuff/amulet/amulet11.gif></td><td><b>Название:</b> Царское ожерелье<br><b>Материал: </b> 2 Золота, 4 Розовый Сапфир, 1 Аметист<br><b>Необходимый ";
echo "навык:</b> 20 уроков</td></tr>\r\n<tr><td width=70 align=center><img src=maingame/pic/stuff/ring/ring2.gif></td><td><b>Название:</b> Кольцо Льда<br><b>Материал: </b> 2 Железа, 3 Голубой Сапфир<br><b>Необходимый навык:</b> 24 урока</td></tr>\r\n<tr><td width=70 align=center><img src=maingame/pic/stuff/amulet/amulet8.gif></td><td><b>Название:</b> Ожерелье мертвеца<br><b>Материал: </b> 2 Железа, 2 Аметист, 2 Голубой Сапфир<br><b>Необ";
echo "ходимый навык:</b> 28 уроков</td></tr>\r\n<tr><td width=70 align=center><img src=maingame/pic/stuff/ring/ring11.gif></td><td><b>Название:</b> Кольцо Тора<br><b>Материал: </b> 2 Золота, 2 Розовый Сапфир, 3 Голубой Сапфир<br><b>Необходимый навык:</b> 32 урока</td></tr>\r\n<tr><td width=70 align=center><img src=maingame/pic/stuff/amulet/amulet9.gif></td><td><b>Название:</b> Ожерелье Фараона<br><b>Материал: </b> 2 Золота, 3 Розовый ";
echo "Сапфир, 3 Голубой Сапфир<br><b>Необходимый навык:</b> 33 урока</td></tr>\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n</table>\r\n<br>\r\n<div align=\"center\"><b>Изготовление драгоценных предметов</b></div><br>\r\n\r\n<div align=\"justify\" class=small>\r\nПрочитайте содержимое свитка, нажав на него в инвентаре, после чего найдите подходящую комнату с функцией кузницы.<br><br>\r\n<div align=center><img src=help/black.gif border=1></div><br>\r\nЗа";
echo "полните появившуюся форму в соответствии со свитком и нажмите на кнопку <b>'Изготовить'</b>.<br><br>\r\nПри неудачной попытке отнимется только по 1 единицы каждого ресурса.\r\n\r\n</div><br>\r\n<br>\r\n<br>\r\n<b><div align=\"center\"><a href=index.php?load=";
print "{$load}";
echo "&show=";
print $show;
echo ">Назад</div></b><br>\r\n";
?>
