<?php

echo "<div align=\"center\"><b>Ткачество</b> (33)</div>\r\n<br>\r\n\r\n<div align=\"justify\" class=small>\r\nПознания в этом умении дают вашему персонажу возможность шить предметы. Вам понадобятся находиться в около ткацкого станка  и иметь в руках подходящие материалы и свиток желаемого предмета. Используйте функции ткацкого станка для создания интересующего Вас предмета. Чем выше Ваше знание в этом умении, чем больше ";
echo "шанс изготовить предмет с повышенными характеристиками.\r\n</div><br>\r\n<div align=\"center\"><b>Таблица изготовления лёгких доспехов</b></div>\r\n<table width=90% align=center>\r\n<tr><td width=70 align=center><img src=maingame/pic/stuff/boots/boots5.gif></td><td><b>Название:</b> Сапоги<br><b>Материал: </b> 4 Ниток, 4 Грубая шерсть<br><b>Необходимый навык:</b> 1 урок</td></tr>\r\n<tr><td width=70 align=center><img src=maingame/pic/";
echo "stuff/boots/boots4.gif></td><td><b>Название:</b> Кожаные сапоги<br><b>Материал: </b> 4 Прочных ниток, 4 Кожа<br><b>Необходимый навык:</b> 5 уроков</td></tr>\r\n<tr><td width=70 align=center><img src=maingame/pic/stuff/glove/glove8.gif></td><td><b>Название:</b> Кожаные рукавицы<br><b>Материал: </b> 5 Ниток, 8 Грубой шерсти<br><b>Необходимый навык:</b> 9 уроков</td></tr>\r\n<tr><td width=70 align=center><img src=maingame/pic/stuff/c";
echo "loak/cloak2.gif></td><td><b>Название:</b> Лёгкий плащ<br><b>Материал: </b> 8 Ниток, 6 Грубой шерсти<br><b>Необходимый навык:</b> 13 уроков</td></tr>\r\n<tr><td width=70 align=center><img src=maingame/pic/stuff/boots/boots2.gif></td><td><b>Название:</b> Вязаные сапоги<br><b>Материал: </b> 4 Прочных ниток, 4 Кожа, 4 Шерсть<br><b>Необходимый навык:</b> 18 уроков</td></tr>\r\n<tr><td width=70 align=center><img src=maingame/pic/stuff/a";
echo "rmor/armor2.gif></td><td><b>Название:</b> Военные доспехи<br><b>Материал: </b> 6 Прочных ниток, 4 Кожи, 4 Шерсти<br><b>Необходимый навык:</b> 24 урока</td></tr>\r\n<tr><td width=70 align=center><img src=maingame/pic/stuff/cloak/cloak3.gif></td><td><b>Название:</b> Плащ некроманта<br><b>Материал: </b> 5 Золотых ниток, 6 Кожи<br><b>Необходимый навык:</b> 28 уроков</td></tr>\r\n<tr><td width=70 align=center><img src=maingame/pic/stuf";
echo "f/cloak/cloak6.gif></td><td><b>Название:</b> Бархатный плащ<br><b>Материал: </b> 8 Прочных ниток, 5 Кожи, 5 Шерсти<br><b>Необходимый навык:</b> 30 уроков</td></tr>\r\n<tr><td width=70 align=center><img src=maingame/pic/stuff/cloak/cloak5.gif></td><td><b>Название:</b> Магический плащ<br><b>Материал: </b> 8 Золотых ниток, 6 Кожи, 4 Шерсти<br><b>Необходимый навык:</b> 33 урока</td></tr>\r\n\r\n</table>\r\n<br>\r\n<div align=\"center\"><b>Изго";
echo "товление лёгких доспехов</b></div><br>\r\n\r\n<div align=\"justify\" class=small>\r\nПрочитайте содержимое свитка, нажав на него в инвентаре, после чего найдите подходящую комнату с функцией кузницы.<br><br>\r\n<div align=center><img src=help/black.gif border=1></div><br>\r\nЗаполните появившуюся форму в соответствии со свитком и нажмите на кнопку <b>'Изготовить'</b>.<br><br>\r\nПри неудачной попытке отнимется только по 1 ед";
echo "иницы каждого ресурса.\r\n\r\n</div><br>\r\n<br>\r\n<br>\r\n<b><div align=\"center\"><a href=index.php?load=";
print "{$load}";
echo "&show=";
print $show;
echo ">Назад</div></b><br>\r\n";
?>
