<?php

echo "<div align=\"center\"><b>Столярное дело</b> (40)</div>\r\n<br>\r\n\r\n<div align=\"justify\" class=small>\r\nПознания в этом умении дают вашему персонажу возможность изготавливать посохи и луки из дерева и ювелирных камней. Вам понадобятся находиться в около Столярной мастерской и иметь в руках подходящие материалы и свиток желаемого предмета. Используйте функции Столярной для создания интересующего Вас предмета. Ч";
echo "ем выше Ваше знание в этом умении, чем больше шанс изготовить предмет с повышенными характеристиками.\r\n</div><br>\r\n<div align=\"center\"><b>Таблица изготовления столярных предметов</b></div>\r\n<table width=90% align=center>\r\n<tr><td width=70 align=center><img src=maingame/pic/stuff/bow/arrows.gif></td><td><b>Название:</b> Стрелы<br><b>Материал: </b> 3 Берёзы<br><b>Необходимый навык:</b> 1 урок</td></tr>\r\n<tr><td width=70 al";
echo "ign=center><img src=maingame/pic/stuff/bow/bow1.gif></td><td><b>Название:</b> Лук<br><b>Материал: </b> 4 Орешника<br><b>Необходимый навык:</b> 4 урока</td></tr>\r\n<tr><td width=70 align=center><img src=maingame/pic/stuff/stuff/stuff2.gif></td><td><b>Название:</b> Магическая палка<br><b>Материал: </b> 4 Орешника<br><b>Необходимый навык:</b> 8 уроков</td></tr>\r\n<tr><td width=70 align=center><img src=maingame/pic/stuff/bow/bow5.gif";
echo "></td><td><b>Название:</b> Арбалет<br><b>Материал: </b> 7 Берёза, 3 Ясень<br><b>Необходимый навык:</b> 12 урока</td></tr>\r\n<tr><td width=70 align=center><img src=maingame/pic/stuff/stuff/stuff1.gif></td><td><b>Название:</b> Посох<br><b>Материал: </b> 4 Берёзы, 2 Розовый Сапфир<br><b>Необходимый навык:</b> 15 уроков</td></tr>\r\n<tr><td width=70 align=center><img src=maingame/pic/stuff/bow/arrows.gif></td><td><b>Название:</b> Огненны";
echo "е стрелы<br><b>Материал: </b> 4 Дуб<br><b>Необходимый навык:</b> 15 урок</td></tr>\r\n<tr><td width=70 align=center><img src=maingame/pic/stuff/bow/bow3.gif></td><td><b>Название:</b> Лук охотника<br><b>Материал: </b> 4 Берёза, 8 Ясень<br><b>Необходимый навык:</b> 18 урока</td></tr>\r\n<tr><td width=70 align=center><img src=maingame/pic/stuff/stuff/stuff3.gif></td><td><b>Название:</b> Посох старца<br><b>Материал: </b> 4 Ясеня, 5 Розов";
echo "ый Сапфир<br><b>Необходимый навык:</b> 22 уроков</td></tr>\r\n<tr><td width=70 align=center><img src=maingame/pic/stuff/bow/bow4.gif></td><td><b>Название:</b> Тяжёлый арбалет<br><b>Материал: </b> 10 Дуб, 5 Бук<br><b>Необходимый навык:</b> 26 урока</td></tr>\r\n<tr><td width=70 align=center><img src=maingame/pic/stuff/stuff/stuff6.gif></td><td><b>Название:</b> Посох огня<br><b>Материал: </b> 5 Дуб, 4 Аметист<br><b>Необходимый навык:</";
echo "b> 26 урока</td></tr>\r\n<tr><td width=70 align=center><img src=maingame/pic/stuff/stuff/stuff5.gif></td><td><b>Название:</b> Посох холода<br><b>Материал: </b> 8 Дуб, 8 Аметист<br><b>Необходимый навык:</b> 35 уроков</td></tr>\r\n<tr><td width=70 align=center><img src=maingame/pic/stuff/bow/arrows.gif></td><td><b>Название:</b> Cтрелы вампира<br><b>Материал: </b> 4 Бук, 3 Аметист<br><b>Необходимый навык:</b> 37 урок</td></tr>\r\n<tr><td w";
echo "idth=70 align=center><img src=maingame/pic/stuff/bow/bow2.gif></td><td><b>Название:</b> Тяжёлый лук<br><b>Материал: </b> 16 Бук<br><b>Необходимый навык:</b> 40 урока</td></tr>\r\n<tr><td width=70 align=center><img src=maingame/pic/stuff/stuff/stuff4.gif></td><td><b>Название:</b> Магический жезл<br><b>Материал: </b> 10 Бук, 8 Голубой Сапфир<br><b>Необходимый навык:</b> 40 уроков</td></tr>\r\n\r\n\r\n</table>\r\n<br>\r\n<div align=\"center\"><b";
echo ">Изготовление лёгких доспехов</b></div><br>\r\n\r\n<div align=\"justify\" class=small>\r\nПрочитайте содержимое свитка, нажав на него в инвентаре, после чего найдите подходящую комнату с функцией столярной.<br><br>\r\n<div align=center><img src=help/black.gif border=1></div><br>\r\nЗаполните появившуюся форму в соответствии со свитком и нажмите на кнопку <b>'Изготовить'</b>.<br><br>\r\nПри неудачной попытке отнимется только ";
echo "по 1 единицы каждого ресурса.\r\n\r\n</div><br>\r\n<br>\r\n<br>\r\n<b><div align=\"center\"><a href=index.php?load=";
print "{$load}";
echo "&show=";
print $show;
echo ">Назад</div></b><br>\r\n";
?>
