<table width=100% aling=center cellpadding=2><tr><td><table cellpadding=1 cellspacing=0 border=0><tr><td><b>Дата:</b> 25 Февраля 2015 </td></tr></tr><td><table cellpadding=0 cellspacing=0 bgcolor=A7BEC2 width=100% height=1 border=0><tr><td></td></tr></table></td></tr></table></td>
<td align=right><table cellpadding=1 cellspacing=0 border=0><tr><td align=right><b>Отправитель:</b> Goldot </td></tr></tr><td><table cellpadding=0 cellspacing=0 bgcolor=A7BEC2 width=100% height=1 border=0><tr><td></td></tr></table></td></tr></table></td></tr><tr><td colspan=2>
Локвуд был вновь открыт!<br>
Портал вы найдете недалеко от Морены, вход доступен с 60 уровня.<br>
Обращаем ваше внимание на то, что администрация оставляет за собой право на изменения параметров выбитых в Локвуде вещей в результате тестов </td></tr></table><br><table cellpadding=0 cellspacing=0 bgcolor=A7BEC2 width=90% height=1 border=0 align=center><tr><td></td></tr></table><table width=100% aling=center cellpadding=2><tr><td><table cellpadding=1 cellspacing=0 border=0><tr><td><b>Дата:</b> 22 Февраля 2015 </td></tr></tr><td><table cellpadding=0 cellspacing=0 bgcolor=A7BEC2 width=100% height=1 border=0><tr><td></td></tr></table></td></tr></table></td>
<td align=right><table cellpadding=1 cellspacing=0 border=0><tr><td align=right><b>Отправитель:</b> Goldot </td></tr></tr><td><table cellpadding=0 cellspacing=0 bgcolor=A7BEC2 width=100% height=1 border=0><tr><td></td></tr></table></td></tr></table></td></tr><tr><td colspan=2>
Скорость набора опыта вернулась к норме, рейт х2 был отключен.<br>
Однако, по просьбам игроков, каждые выходные двухкратное увеличение опыта будет действовать.<br><br>
Были удалены вещи, выбитые при тестировании Локвуда, доступ в данную локацию будет открыт в ближайшие дни.<br><br>
Также сообщаем, что в скором времени будет пересмотрена таблица опыта, требуемого для получения уровней. </td></tr></table><br><table cellpadding=0 cellspacing=0 bgcolor=A7BEC2 width=90% height=1 border=0 align=center><tr><td></td></tr></table><table width=100% aling=center cellpadding=2><tr><td><table cellpadding=1 cellspacing=0 border=0><tr><td><b>Дата:</b> 19 Февраля 2015 </td></tr></tr><td><table cellpadding=0 cellspacing=0 bgcolor=A7BEC2 width=100% height=1 border=0><tr><td></td></tr></table></td></tr></table></td>
<td align=right><table cellpadding=1 cellspacing=0 border=0><tr><td align=right><b>Отправитель:</b> Goldot </td></tr></tr><td><table cellpadding=0 cellspacing=0 bgcolor=A7BEC2 width=100% height=1 border=0><tr><td></td></tr></table></td></tr></table></td></tr><tr><td colspan=2>
Уважаемые игроки!
Как сообщалось ранее, персонаж <a href="/fullinfo.php?name=Phobos" target=_blank><b>Phobos</b></a> покинул команду проекта. <br> <br>
Верховным вершителем судеб отныне является <a href="/fullinfo.php?name=Sombre" target=_blank><b>Sombre</b></a>,<br> ее младшим братом - <a href="/fullinfo.php?name=Goldot" target=_blank><b>Goldot</b></a> </td></tr></table><br><table cellpadding=0 cellspacing=0 bgcolor=A7BEC2 width=90% height=1 border=0 align=center><tr><td></td></tr></table><table width=100% aling=center cellpadding=2><tr><td><table cellpadding=1 cellspacing=0 border=0><tr><td><b>Дата:</b> 15 Февраля 2015 </td></tr></tr><td><table cellpadding=0 cellspacing=0 bgcolor=A7BEC2 width=100% height=1 border=0><tr><td></td></tr></table></td></tr></table></td>
<td align=right><table cellpadding=1 cellspacing=0 border=0><tr><td align=right><b>Отправитель:</b> Phobos </td></tr></tr><td><table cellpadding=0 cellspacing=0 bgcolor=A7BEC2 width=100% height=1 border=0><tr><td></td></tr></table></td></tr></table></td></tr><tr><td colspan=2>
Уважаемые игроки ! В связи с отсутствием времени заниматься проектом было принято решение продать его. У всех у кого остались вопросы просьба связаться со мной в течении 3 дней.

Спасибо за то что были рядом !  </td></tr></table><br><table cellpadding=0 cellspacing=0 bgcolor=A7BEC2 width=90% height=1 border=0 align=center><tr><td></td></tr></table><table width=100% aling=center cellpadding=2><tr><td><table cellpadding=1 cellspacing=0 border=0><tr><td><b>Дата:</b> 2 Февраля 2015 </td></tr></tr><td><table cellpadding=0 cellspacing=0 bgcolor=A7BEC2 width=100% height=1 border=0><tr><td></td></tr></table></td></tr></table></td>
<td align=right><table cellpadding=1 cellspacing=0 border=0><tr><td align=right><b>Отправитель:</b> Phobos </td></tr></tr><td><table cellpadding=0 cellspacing=0 bgcolor=A7BEC2 width=100% height=1 border=0><tr><td></td></tr></table></td></tr></table></td></tr><tr><td colspan=2>
Внимание ! Сегодня 2 февраля 2015 года в период с 19-00 до 23-00 возможны перебои в работе сервера .<br>
Приносим свои извинения за доставленные неудобства . В связи с этим по окончанию проф. работ будут включены рейты на х2 <br><br>
Спасибо что вы с нами!!!

p.s. Персонаж Нельсон награжден кольцом Древних <img src="/maingame/pic/stuff/ring/troll.gif"> </td></tr></table><br><table cellpadding=0 cellspacing=0 bgcolor=A7BEC2 width=90% height=1 border=0 align=center><tr><td></td></tr></table>